version: '3.8'
services:
  vlexid-back:
    build: .
    container_name: vlexid-back
    volumes:
      - .:/git/vlexid-back
    ports:
      - 3000:3000
    environment:
      HOST: $HOST
      DB_PORT: $DB_PORT
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD
      DATABASE: $DATABASE
      PORT: $PORT
    networks:
      - reverseproxy-nw
      
networks:
  reverseproxy-nw:
    external: true
